#!/usr/bin/env python3

import subprocess
import pytest
from pathlib import Path


class TestEmitD:
    @classmethod
    def setup_class(cls):
        cls.project_root = Path(__file__).parent.parent
        cls.compiler_path = cls.project_root / "duende"
        cls.examples_dir = cls.project_root / "examples"

        # Build compiler if it doesn't exist
        if not cls.compiler_path.exists():
            subprocess.run(["dub", "build"], cwd=cls.project_root, check=True)

    def test_emit_d_flag(self):
        """Test that --emit-d generates D files and prints mappings without building executable"""
        source_file = self.examples_dir / "emit_d_demo.du"
        
        # Ensure the source file exists
        assert source_file.exists(), f"Source file {source_file} does not exist"
        
        # Run duende with --emit-d flag
        result = subprocess.run(
            [str(self.compiler_path), "--emit-d", str(source_file)],
            capture_output=True,
            text=True,
            cwd=self.project_root
        )
        
        # Should succeed
        assert result.returncode == 0, f"Compilation failed: {result.stderr}"
        
        # Should print module mappings
        lines = result.stdout.strip().split('\n')
        assert len(lines) >= 1, "Expected at least one module mapping"
        
        # Each line should have format "moduleName => path"
        for line in lines:
            if line.strip():  # Skip empty lines
                assert " => " in line, f"Invalid mapping format: {line}"
                module_name, d_path = line.split(" => ", 1)
                assert module_name.strip(), f"Empty module name in: {line}"
                assert d_path.strip().endswith(".d"), f"D file should end with .d: {line}"
                # Verify the D file was actually created
                d_file_path = Path(d_path.strip())
                assert d_file_path.exists(), f"D file not found: {d_path}"
        
        # Verify no executable was built
        build_dir = source_file.parent / "duende_build"
        executable = build_dir / source_file.stem
        assert not executable.exists(), f"Executable should not be built with --emit-d: {executable}"

    def test_emit_d_with_existing_example(self):
        """Test --emit-d with an existing example that we know works"""
        source_file = self.examples_dir / "variables.du"
        
        # Run duende with --emit-d flag
        result = subprocess.run(
            [str(self.compiler_path), "--emit-d", str(source_file)],
            capture_output=True,
            text=True,
            cwd=self.project_root
        )
        
        # Should succeed
        assert result.returncode == 0, f"Compilation failed: {result.stderr}"
        
        # Should print module mappings
        assert result.stdout.strip(), "Expected output with module mappings"
        
        # Verify no executable was built
        build_dir = source_file.parent / "duende_build"
        executable = build_dir / source_file.stem
        assert not executable.exists(), f"Executable should not be built with --emit-d: {executable}"

    def test_emit_d_vs_normal_compilation(self):
        """Test that --emit-d generates the same D files as normal compilation"""
        source_file = self.examples_dir / "basic_arithmetic.du"
        
        # First, run with --emit-d
        emit_result = subprocess.run(
            [str(self.compiler_path), "--emit-d", str(source_file)],
            capture_output=True,
            text=True,
            cwd=self.project_root
        )
        assert emit_result.returncode == 0
        
        # Parse the mappings to get D file paths
        emit_d_files = []
        for line in emit_result.stdout.strip().split('\n'):
            if line.strip() and " => " in line:
                _, d_path = line.split(" => ", 1)
                emit_d_files.append(Path(d_path.strip()))
        
        # Store content of D files generated by --emit-d
        emit_d_contents = {}
        for d_file in emit_d_files:
            if d_file.exists():
                emit_d_contents[d_file.name] = d_file.read_text()
        
        # Now run normal compilation
        normal_result = subprocess.run(
            [str(self.compiler_path), str(source_file)],
            capture_output=True,
            text=True,
            cwd=self.project_root
        )
        assert normal_result.returncode == 0
        
        # Compare D file contents - they should be identical
        for d_file in emit_d_files:
            if d_file.exists():
                normal_content = d_file.read_text()
                emit_content = emit_d_contents.get(d_file.name, "")
                assert normal_content == emit_content, f"D file content differs: {d_file}"